version: 2.1

jobs:
 # THIS IS SECURITY SENSITVE
 # READ THESE
 # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
 # https://discuss.circleci.com/t/adding-ssh-keys-fails/7747/24
 deploy-github-pages:
  docker:
   - image: nixorg/nix:circleci
  steps:
   - checkout
   - add_ssh_keys:
      fingerprints:
       - "0b:fd:8f:62:37:9f:5f:54:f8:3d:7e:c6:f1:17:fd:57"
   - run:
      name: Deploy github pages
      command: |
       git config user.name "$GITHUB_PAGES_DEPLOY_USER"
       git config user.email "$GITHUB_PAGES_DEPLOY_EMAIL"
       git remote add deploy git@github.com:artbrock/artbrock.com.git
       nix-shell --run nix-deploy

workflows:
 version: 2.1
 deploy:
  jobs:
   - deploy-github-pages:
      filters:
       branches:
        only: master
