version: 2.1

jobs:
 # THIS IS SECURITY SENSITVE
 # READ THESE
 # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
 # https://discuss.circleci.com/t/adding-ssh-keys-fails/7747/24
 deploy-github-pages:
  docker:
   - image: nixorg/nix:circleci
  steps:
   - add_ssh_keys:
      fingerprints:
       - "6c:4d:7f:d4:f6:f5:89:13:21:c4:77:98:38:28:82:ca"
   - checkout
   - run:
      name: Deploy github pages
      command: |
       git config user.name "$GITHUB_PAGES_DEPLOY_USER"
       git config user.email "$GITHUB_PAGES_DEPLOY_EMAIL"
       nix-shell --run nix-deploy

workflows:
 version: 2.1
 deploy:
  jobs:
   - deploy-github-pages:
      filters:
       branches:
        only: master
