version: 2.1

jobs:
 # THIS IS SECURITY SENSITVE
 # READ THESE
 # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
 # https://discuss.circleci.com/t/adding-ssh-keys-fails/7747/24
 deploy-github-pages:
  docker:
   - image: nixorg/nix:circleci
  steps:
   - checkout
   - add_ssh_keys:
      fingerprints:
       - "f3:2b:02:e4:71:8f:fc:8b:85:33:c7:34:4f:40:bd:64"
   - run:
      name: Deploy github pages
      command: |
       git config user.name "$GITHUB_PAGES_DEPLOY_USER"
       git config user.email "$GITHUB_PAGES_DEPLOY_EMAIL"
       git remote add deploy git@github.com:artbrock/artbrock.com.git
       nix-shell --run nix-deploy

workflows:
 version: 2.1
 deploy:
  jobs:
   - deploy-github-pages:
      filters:
       branches:
        only: master
